const projects = [
  { title: "职序 ZHIXU", eyebrow: "求职机会与决策工作台", description: "把招聘截图、JD、链接和文件，转化为可确认、可比较、可投递、可跟踪的求职机会。", image: "/zhixu-cover.svg", href: "/projects/zhixu", tags: ["AI 产品", "独立设计与开发"] },
  { title: "Threadline", eyebrow: "项目变化执行智能体", description: "从分散项目上下文识别变化与影响，在分级审批后执行，并验证行动是否真正完成。", image: "/threadline-cover.png", href: "/projects/threadline", tags: ["智能体设计", "可信执行"] },
  { title: "Signal", eyebrow: "个人收藏整理工具", description: "保留原始来源和完整语境，把散落素材整理成可检索、可行动、可持续维护的个人信息空间。", image: "/signal-cover.svg", href: "/projects/signal", tags: ["信息架构", "AI 整理"] },
];

export default function Home() {
  return <main className="site-home">
    <header className="site-nav" data-site-nav><a className="site-brand" href="#home"><span>ZC</span><b>张灿</b></a><nav aria-label="主导航"><a href="#home" data-nav-section="home">首页</a><a href="#portfolio" data-nav-section="portfolio">作品集</a><a href="#about" data-nav-section="about">关于我</a><a href="/resume.pdf" download>简历下载</a><a href="#contact" data-nav-section="contact">联系方式</a></nav></header>
    <section className="minimal-hero" id="home"><div className="hero-aura" aria-hidden="true"/><div className="hero-content reveal-group"><p className="eyebrow"><i/> 2026 年产品实习求职中</p><h1>张灿</h1><p className="hero-role">AI 产品方向求职者</p><p className="hero-value">把复杂的 AI 能力，设计成用户能理解、能信任、也真正愿意使用的产品。</p><div className="hero-actions"><a className="button button-primary" href="#portfolio">浏览作品集 <span>↓</span></a><a className="button button-secondary" href="/resume.pdf" download>下载简历 <span>↗</span></a></div></div><a className="scroll-cue" href="#portfolio"><span/> 向下浏览</a></section>
    <section className="section portfolio-section" id="portfolio"><div className="section-shell"><header className="section-heading reveal-group"><div><p className="eyebrow">项目作品</p><span>3 个真实产品项目</span></div><h2>从问题判断，<br/>到可运行产品。</h2></header><div className="project-grid">{projects.map((project,index)=><a className="project-card reveal-card" href={project.href} key={project.title}><div className="project-media"><img src={project.image} alt={`${project.title} 产品预览`}/><span className="project-index">0{index+1}</span><span className="project-open">进入完整案例 ↗</span></div><div className="project-info"><p>{project.eyebrow}</p><h3>{project.title}</h3><span>{project.description}</span><ul>{project.tags.map(tag=><li key={tag}>{tag}</li>)}</ul></div></a>)}</div></div></section>
    <section className="section about-section" id="about"><div className="section-shell"><header className="section-heading about-heading reveal-group"><div><p className="eyebrow">个人信息</p><span>四川大学 · GPA 3.69 / 4.00</span></div><h2>关于我</h2></header><div className="about-intro reveal-card"><p>我是张灿，四川大学管理专业本科生。工科转入管理的经历，让我习惯同时理解系统如何运转，以及用户为什么这样行动。</p><p>我关注 AI 产品的信息可信、决策解释与自动化权限，并通过职序、Threadline 和 Signal 三个项目持续实践产品设计与开发。</p></div><div className="about-grid"><article className="glass-panel reveal-card"><p className="panel-label">实习经历</p><h3>百词斩 · AIGC 内容量产助理</h3><span>2025.06 — 2025.09</span><p>参与 Prompt 体系迭代、内容质量标准与 Bad Case 治理，用评测与反馈闭环管理模型的不确定性。</p></article><article className="glass-panel reveal-card"><p className="panel-label">技能</p><div className="skill-groups"><div><b>产品</b><span>用户场景 / 需求拆解 / MVP / PRD / 原型 / 验收</span></div><div><b>AI</b><span>Prompt / JSON Schema / 评测 / Bad Case 归因</span></div><div><b>技术</b><span>API / React / TypeScript / Next.js / 数据流</span></div></div></article><article className="glass-panel value-panel reveal-card"><p className="panel-label">工作能力</p><h3>我能为团队创造什么</h3><ul><li><span>01</span>把模糊 AI 想法拆成可验证的问题</li><li><span>02</span>把能力边界转化为交互与状态规则</li><li><span>03</span>用真实证据和版本迭代持续改善结果</li></ul></article><article className="glass-panel honors-panel reveal-card"><p className="panel-label">荣誉与经历</p><ul><li><b>2024</b><span>国家励志奖学金</span></li><li><b>成员</b><span>百度飞桨领航团核心成员</span></li><li><b>英语</b><span>英语六级</span></li></ul></article></div><a className="button button-secondary resume-bottom" href="/resume.pdf" download>下载完整 PDF 简历 <span>↓</span></a></div></section>
    <section className="section contact-section" id="contact"><div className="section-shell contact-shell reveal-group"><p className="eyebrow">联系方式</p><h2>联系我</h2><p className="contact-note">AI 产品实习 / 产品经理实习</p><a className="contact-email" href="mailto:zc_xingshan@qq.com">zc_xingshan@qq.com <span>↗</span></a><div className="contact-meta"><span>成都 / 可实习</span><span>四川大学 · 管理专业</span><a href="/resume.pdf" download>下载简历 ↓</a></div></div></section>
  </main>;
}
