import ProjectBrowser from "./ProjectBrowser";

export default function Home(){return <main className="portfolio-home">
 <header className="portfolio-nav" data-site-nav><a href="#home" className="portfolio-logo">张灿</a><nav><a href="#work" data-nav-section="work">项目</a><a href="/about">关于我</a><a href="/resume.pdf" download>简历</a><a href="mailto:zc_xingshan@qq.com">联系</a></nav></header>
 <section className="intro-layout" id="home"><div className="intro-main"><p>AI 产品 / 产品经理实习</p><h1>张灿</h1><h2>四川大学本科生，具有 AIGC 内容生产与模型评测经验，独立完成 3 个 AI 产品项目。</h2></div><aside><div><span>方向</span><b>AI 产品 · 产品经理</b></div><div><span>教育</span><b>四川大学 · GPA 3.69 / 4.00</b></div><div><span>实习</span><b>百词斩 · AIGC 内容量产助理</b></div><div className="intro-links"><a href="#work">查看项目 ↓</a><a href="/resume.pdf" download>下载简历 ↗</a></div></aside></section>
 <ProjectBrowser/>
 <section className="home-about-full" id="about"><header><div><span>关于我</span><h2>张灿</h2></div><p>四川大学管理专业本科生，工科转入管理的经历让我习惯同时理解系统如何运转、用户为什么这样行动，以及一个方案如何真正落地。</p></header><div className="home-about-columns"><article><span>实习经历</span><h3>百词斩 · AIGC 内容量产助理</h3><p>参与 Prompt 体系迭代、内容质量标准和 Bad Case 治理，通过评测、归因与反馈闭环处理模型输出的不确定性。</p></article><article><span>产品能力</span><h3>从需求到可操作原型</h3><p>能够完成用户场景、需求拆解、信息架构、MVP、PRD、交互原型、验收标准与版本迭代。</p></article><article><span>AI 与技术</span><h3>理解能力，也处理边界</h3><p>熟悉结构化输出、模型评测、人工确认与权限设计，并使用 React、TypeScript 和模型 API 实现产品。</p></article></div><footer><div><span>教育</span><b>四川大学 · GPA 3.69 / 4.00</b></div><div><span>项目</span><b>职序 / Threadline / Signal</b></div><div><span>英语</span><b>英语六级</b></div><a href="/about">查看完整个人介绍 ↗</a></footer></section>
 <footer className="portfolio-footer"><div><h2>联系我</h2><a href="mailto:zc_xingshan@qq.com">zc_xingshan@qq.com ↗</a></div><aside><span>AI 产品实习 / 产品经理实习</span><span>成都 · 可实习</span><span>© 2026 张灿</span></aside></footer>
 </main>}
