"use client";
import { useState } from "react";

const projects=[
 {name:"职序 ZHIXU",type:"求职机会与决策工作台",status:"可运行产品",image:"/zhixu-cover.svg",href:"/projects/zhixu",summary:"把分散的招聘材料变成可以判断、比较、投递和持续跟踪的真实机会。",role:"产品设计 / AI 工作流 / 开发",problem:"招聘截图、JD、网申链接和准备材料散落在不同位置，用户难以判断优先级，也无法连续跟进一次投递。",solution:"建立来源—岗位—机会—投递阶段的数据关系，先核对硬性条件，再用岗位要求与个人证据矩阵解释判断。",delivery:"已实现多源导入、字段确认、重复检测、岗位比较、投递看板及职序 Clip 浏览器扩展。",states:[{name:"导入来源",detail:"保存 JD、链接、截图、PDF 与原始快照，避免整理结果替代原始招聘信息。"},{name:"确认岗位",detail:"不确定字段保持为空，疑似重复只提示、不自动删除，由用户完成关键事实确认。"},{name:"解释判断",detail:"先检查硬性条件，再用岗位要求—经历证据—判断—建议矩阵说明匹配关系。"},{name:"推进投递",detail:"把机会与投递阶段、任务、简历版本、面试准备和复盘关联起来。"}]},
 {name:"Threadline",type:"项目变化执行智能体",status:"可交互原型",image:"/threadline-cover.png",href:"/projects/threadline",summary:"让会议和聊天里的项目变化，经过证据、影响与权限判断后进入可信执行。",role:"问题定义 / 权限系统 / 原型",problem:"真实变化先发生在会议、聊天和文件中，传统看板依赖人工更新；AI若直接执行，又可能把误判放大到整个团队。",solution:"把捕获、证据、影响分析、风险分级、人工审批、执行回执连接成完整状态链。",delivery:"已完成变化捕获、影响判断、四级权限规则、审批与验证闭环的可交互产品原型。",states:[{name:"捕获变化",detail:"从会议、聊天、文件和通知中区分事实、建议、风险与未确认决定。"},{name:"返回证据",detail:"每项判断都能回到原始录音或文字，用户不必盲信模型给出的结论。"},{name:"分析影响",detail:"定位受到影响的任务、材料、项目节点和相关人员，并展示影响范围。"},{name:"审批执行",detail:"高风险动作逐项确认，极高风险强制审批，同时保留执行回执与回滚入口。"}]},
 {name:"Signal",type:"个人收藏整理工具",status:"本地可运行产品",image:"/signal-cover.svg",href:"/projects/signal",summary:"保留完整内容和原始来源，让收藏不只被存下，还能被找到、编辑和再次使用。",role:"信息架构 / AI 交互 / 开发",problem:"收藏工具容易把材料拆成摘要、标签和待办，原始语境随之丢失；保存得越多，重新找到和使用越困难。",solution:"先理解整份材料，再决定是否拆分；整理结果始终和原文、来源引用及人工确认状态共同保存。",delivery:"已实现收集箱、搜索过滤、收藏置顶、分类、区块编辑、拖拽排序、子任务与本地持久化。",states:[{name:"保留原文",detail:"收藏时保存完整内容和原始来源，让用户随时可以返回当时的上下文。"},{name:"整体理解",detail:"模型先理解整份材料，只有主题完全无关时才建议拆成多条记录。"},{name:"确认整理",detail:"AI 可以调整标题、顺序与区块，但不能改变原意；低置信结果等待用户确认。"},{name:"再次使用",detail:"通过搜索、标签、分类、区块编辑、子任务和截止时间让内容重新进入行动。"}]},
];

export default function ProjectBrowser(){const[active,setActive]=useState(0);const[state,setState]=useState(0);const project=projects[active];return <section className="project-browser" id="work"><header><div><span>代表项目</span><h2>从问题定义到可操作产品</h2></div><p>三个项目均由我完成核心产品设计与原型实现。选择项目和流程状态，可直接了解产品如何工作。</p></header><div className="browser-shell"><nav aria-label="选择项目">{projects.map((item,i)=><button className={active===i?"active":""} onClick={()=>{setActive(i);setState(0)}} key={item.name}><span>0{i+1}</span><div><b>{item.name}</b><small>{item.type}</small></div><i>↗</i></button>)}</nav><div className="browser-stage"><div className="browser-stage-top"><span>{project.status}</span><span>{project.role}</span></div><div className="browser-product" key={project.name}><img src={project.image} alt={`${project.name}产品界面`}/></div><div className="browser-detail"><div><p>{project.type}</p><h3>{project.name}</h3><span>{project.summary}</span></div><a href={project.href}>查看完整案例 ↗</a></div><div className="browser-case-info"><article><span>项目背景</span><p>{project.problem}</p></article><article><span>核心方案</span><p>{project.solution}</p></article><article><span>当前落地</span><p>{project.delivery}</p></article></div><div className="browser-states">{project.states.map((item,i)=><button className={state===i?"active":""} onClick={()=>setState(i)} key={item.name}><span>0{i+1}</span>{item.name}</button>)}<p key={`${active}-${state}`}>{project.states[state].detail}</p></div></div></div></section>}
